version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: Building source
          command: |
            cd src
            dotnet build -c Release
      - run:
          name: Testing, Testing, 123
          command: |
            cd src/Harness.Tests.Unit
            dotnet test
